services:
  db:
    container_name: postgres_database
    image: postgres:14.3
    volumes:
      - postgres-db-nest:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

  api-nest:
    build:
      context: . #En que directorio esta ubicado el Dockerfile
      target: prod
      #Esta instruccion ejecuta el paso (stage) especifico del Dockerfile
      dockerfile: Dockerfile

    image: patriciobo/api-nest

    container_name: api_nest

    ports:
      - ${PORT}:${PORT}

    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - PORT=${PORT}
      - HOST_API=${HOST_API}
      - JWT_SECRET=${JWT_SECRET}

    restart: always
    working_dir: /app
    command: sh -c "yarn start:dev"
#Usa un volumen externo YA CREADO
volumes:
  postgres-db-nest:
    external: false
